receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  otlphttp/betterstack:
    endpoint: ${env:BETTERSTACK_ENDPOINT}
    headers:
      Authorization: "Bearer ${env:BETTERSTACK_TOKEN}"

processors:
  batch:
    # Optional optimized batch settings
    send_batch_size: 100
    timeout: 1s

extensions:
  health_check:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/betterstack]
