receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  otlphttp/betterstack:
    endpoint: ${env:BETTERSTACK_ENDPOINT}
    headers:
      Authorization: "Bearer ${env:BETTERSTACK_TOKEN}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/betterstack]
    metrics/betterstack:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/betterstack]
    logs/betterstack:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/betterstack]
